apiVersion: apps/v1
kind: Deployment
metadata:
  name: depdemo 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxtemp 
  template:
    metadata:
      name: mynginxpod
      labels:
        app: nginxtemp
    spec:
      containers:
      - name: nginxtemp
        image: yaswanthreddy1602/demo:v2
        ports:
        - containerPort: 80
