apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: mono
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod
      labels:
        app: myapp

    spec:
      containers:
      - name: myapp
        image: cazzzzz/mono-withstage
        ports:
        - containerPort: 8080
