apiVersion: v1
kind: Pod
metadata:
  labels:
    run: yash
  name: yash
spec:
  containers:
  - image: yaswanthreddy1602/fast:latest
    name: yash
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
