apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: Banking-Image-Policy
  namespace: banking-app
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: allowed-image-registeries
      match:
        any:
          - resources:
              kinds: 
                - Pod
       validate:
        message: "Error: Images are not allowed from this registry"
        foreach:
          - list: "request.object.spec.containers"
            anyPattern:
              - image: "yaswanthreddy1602/*"
              - image: "thamizhanm3/*"
          - list: "request.object.spec.initContainers"
            anyPattern:
              - image: "yaswanthreddy1602/*"
              - image: "thamizhanm3/*"
